### ISSUE TITLE
Nothing being downloaded

### ISSUE THREAD

**Issue by rere225** [Spade-and-Archer/UltimateFightARR#1]
Hey,

I got everything pretty much setup in my .env, and looks like the npm run start run fine, but won't download anything.

It list a lot of events and  "... 600 more items", but in my qbit nothing is being downloaded.

[output.txt](https://github.com/user-attachments/files/15518459/output.txt)
[output.txt](https://github.com/user-attachments/files/15518459/output.txt)

**Comment by Spade-and-Archer** [comment]
Looks like it's finding the fights, but it doesn't think it should download them. Can you post the contents of your .env file? Obviously with any sensitive information removed.

**Comment by rere225** [comment]
Nevermind! the folder already existed so that's why nothing happened after the listing (no log). Now back to my first error (that I didn't mentioned here)

Seems that the script wants to connect to localhost for qbit client, but the script runs on a VM (windows 11) in Unraid and qBitorrent is in a container (also in the same Unraid host) in bridge mode.

Here's my env:

PROWLARR_KEY="myprowlarrapikey"
PROWLARR_BASE_URL=http://192.168.86.XXX:9696
CHECK_LAST_N_DAYS=30
GET_PRELIMS=true
GET_COUNTDOWN=true
GET_FIGHT_NIGHT=true
GET_ON_ESPN=true
DOWNLOAD_DIRECTORY=Z:\media\UFC\
QBIT_API_USERNAME=admin
QBIT_API_PASS="QBITORRENTWEBAPPPASSWORD"
QBIT_API_PORT=8080


Now if the folders doesn't exist, it seems to show queries, but I get an error to connect:

Query is UFC+Fight+Night+Barboza vs Murphy
found 21 results total
found 21 with UFC in title
found 21 with correct event name
found 11 with Acceptable Quality
found 11 with more than 2 seeders
found 11 smaller than 11 GB
found 11 results that aren't multi-part
found 6 results that are the correct event type
Best result:
{"guid":"TORRETNINDEXER"id=1176078","age":12,"ageHours":304.7536087234722,"ageMinutes":18285.216523415,"size":8632884224,"grabs":127,"indexerId":2,"indexer":"YGGtorrent","title":"UFC.Fight.Night.241.Barboza.vs.Murphy.1080p.WEB-DL.H264.Fight-BB (18/05/2024)","sortTitle":"ufc fight night 241 barboza vs murphy 1080p web dl h264 fight bb 18052024","imdbId":0,"tmdbId":0,"tvdbId":0,"tvMazeId":0,"publishDate":"2024-05-19T04:27:12Z","downloadUrl":"http://192.168.86.248:9696/2/download?apikey="APIKEY"&file=UFC.Fight.Night.241.Barboza.vs.Murphy.1080p.WEB-DL.H264.Fight-BB+(18%2F05%2F2024)","infoUrl":""OTHER INFOs"[]}],"seeders":21,"leechers":0,"protocol":"torrent","fileName":"UFC.Fight.Night.241.Barboza.vs.Murphy.1080p.WEB-DL.H264.Fight-BB (18/05/2024).torrent","eventType":"main","indexerPriority":23}
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1117:18)
    at afterConnectMultiple (node:net:1684:7) {
  code: 'ECONNREFUSED',
  [errors]: [
    Error: connect ECONNREFUSED ::1:8080
        at createConnectionError (node:net:1647:14)
        at afterConnectMultiple (node:net:1677:16) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 8080
    },
    Error: connect ECONNREFUSED 127.0.0.1:8080
        at createConnectionError (node:net:1647:14)
        at afterConnectMultiple (node:net:1677:16) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 8080
    }
  ]
}

Node.js v22.2.0

**Comment by Spade-and-Archer** [comment]
Hmm, yeah. It assumes the QBit is running on localhost. I can add a .env variable to override that and set it to any URL.

**Comment by Spade-and-Archer** [comment]
Released a new version, check the readme for how you define the path to QBittorrent now and let me know if you have further problems :)

**Comment by rere225** [comment]
With the help of one colleague, I made it work by changing AddDownload.ts:

first block to:

export async function loginToQBit(){
    if(!client){
        client = new qBittorrentClient(
            process.env.QBIT_API_URL,
            process.env.QBIT_API_USERNAME,
            process.env.QBIT_API_PASS
        );
        await client.auth.login(
            process.env.QBIT_API_USERNAME,
            process.env.QBIT_API_PASS
        );
        await client.app.version();
    }

}

put process.env.QBIT_API_URL where the localhost is hardcoded.

then in .ENV change the port for the complete IP + Port

**Comment by rere225** [comment]
And....you did it already lol...

**Comment by rere225** [comment]
I also had to **npm run build** to make it work.

**Comment by Spade-and-Archer** [comment]
Glad it did work! Let me know if you have any more problems :)
